update file ai.yml error syntax

diff --git a/.github/workflows/ai.yml b/.github/workflows/ai.yml
--- a/.github/workflows/ai.yml
+++ b/.github/workflows/ai.yml
@@ -1,52 +1,52 @@
 name: Deploy AI Service
 
 on:
-	push:
-		branches:
-			- main
-		paths:
-			- 'apps/ai-service/**'
+  push:
+    branches:
+      - main
+    paths:
+      - 'apps/ai-service/**'
 
 jobs:
-	deploy:
-		runs-on: ubuntu-latest
+  deploy:
+    runs-on: ubuntu-latest
 
-		steps:
-			- name: Checkout code
-				uses: actions/checkout@v4
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-			- name: Login Docker Hub
-				uses: docker/login-action@v3
-				with:
-					username: ${{ secrets.DOCKER_USERNAME }}
-					password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Login Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-			- name: Build & Push Image
-				run: |
-					docker build -t xuanit/ai-service:latest ./apps/ai-service
-					docker push xuanit/ai-service:latest
+      - name: Build & Push Image
+        run: |
+          docker build -t xuanit/ai-service:latest ./apps/ai-service
+          docker push xuanit/ai-service:latest
 
-			- name: Deploy to EC2
-				uses: appleboy/ssh-action@v1.0.3
-				with:
-					host: ${{ secrets.EC2_HOST_AI }}
-					username: ${{ secrets.EC2_USER }}
-					key: ${{ secrets.EC2_SSH_KEY }}
-					script: |
-						cd ~
+      - name: Deploy to EC2
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.EC2_HOST_AI }}
+          username: ${{ secrets.EC2_USER }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            cd ~
 
-						if [ ! -f .env ]; then
-							echo ".env file not found!"
-							exit 1
-						fi
+            if [ ! -f .env ]; then
+              echo ".env file not found!"
+              exit 1
+            fi
 
-						docker pull xuanit/ai-service:latest
+            docker pull xuanit/ai-service:latest
 
-						docker stop ai-service || true
-						docker rm ai-service || true
+            docker stop ai-service || true
+            docker rm ai-service || true
 
-						docker run -d \
-							--name ai-service \
-							-p 50055:50055 \
-							--env-file .env \
-							xuanit/ai-service:latest
+            docker run -d \
+              --name ai-service \
+              -p 50055:50055 \
+              --env-file .env \
+              xuanit/ai-service:latest
